### ISSUE TITLE
Can't do disconnect from within callkit delegate

### ISSUE THREAD

**Issue by homanp** [twilio/voice-callkit-quickstart-objc#1]
Hi @paynerc,

I'm testing different scenarios with the callkit implementation of beta-4 and found one case where it doesn't seem to work properly.
1. Make an outgoing Twilio call
2. Receive an inbound native call to the same device that made the Twilio outbound call.
3. Press End call and Accept.

This triggers the 

`- (void)provider:(CXProvider *)provider performEndCallAction:(CXEndCallAction *)action`

but doing `[self.outgoingCall disconnect];` doesn't seem to work even though there is an outgoing call object in `Connected` state.

Any ideas?

**Comment by bchen-twilio** [comment]
Hi @homanp,

Sorry for getting back to you after 2 days delay.
I remember trying similar case like your before but thought it was a edge case to call the device itself so I didn't really try to fix the problem. I've got one question and hope you could help us clarify - how do you make and receive the call like step 1 & 2? is it a PSTN call to the device itself or is step 1 calling the same identity that is registered on the same device?
And as usual, you know the SDK guys always love to ask others for logs while they are also trying to reproduce and fix the issue :)

Thanks again for trying beta4 and helping us make the SDK great!

**Comment by homanp** [comment]
Hi @bchen-twilio,
No worries! Below are answers to your questions:

Step 1 is a an outgoing call with the TwilioClient SDK.

Step 2 is a cellular PTSN call made to the same device SIM card.

When you're in a call and receive another call the CallKit incoming Call UI is shown with the options to hangup the previous call and answer the new call.

Was that clear enough?

**Comment by bchen-twilio** [comment]
Hi @homanp,
Thanks for the clarifications. Let me explain:
First of all I can also reproduce this issue by calling the PSTN number of the phone itself. The bottom line of this issue is that, the interruption handler method is trying to resume audio after the interruption is ended by step-3. The outgoing call is already disconnected by calling `disconnect` upon the `provider:performEndCallAction:` callback so it makes no sense to resume audio.
In my testing, after calling `disconnect`, the SIP connection did get disconnected, but the audio device is started again by the interruption handler, thus I can see the system red status bar if I go back to the Home screen.
I've tried to add active-call checking in the interruption handler and it seems to work fine now.
Could you share with us what you were seeing after `[self.outgoingCall disconnect]`?

Thanks

**Comment by homanp** [comment]
Hey,
Thanks for the update. I can confirm that I see the red status bar after hitting accept. And that the call is ended. Althogugh I Can't seem to start a new outbound call. Perhaps because the red status bar is still there. Can you share the active-call code you mentioned?

**Comment by bchen-twilio** [comment]
Hi @homanp,
Thanks for getting back with the info. The active-call checking actually needs to happen in the SDK so unfortunately sharing it to you doesn't solve the issue. Sorry.
I tried again w/out the the active-call checking and I was able to make a subsequent outgoing call, just audio was happily playing. After hanging up the call then I made a third outgoing call, audio came back again.

We'll still add the active-call check to make sure the SDK doesn't bring up that red status bar for no reason.

If you could tell us that this is an essential use case for your app... :p
Thanks!

**Comment by homanp** [comment]
Hey,
I think it would be great as user expects the status bar to dissappear after a call is ended. It's pretty confusing right now. 

Just my 2 cents :)

**Comment by bchen-twilio** [comment]
Hey @homanp,
Long time! How's your Twilio app?
Just want to let you know that we have released v2.0.0-beta5 of the Programmable Voice iOS SDK with a couple fixes ([changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)). They are subtle but definitely are making the SDK more robust and more reliable.
Please give it a try and again, we look forward to hearing back your feedbacks!

Thanks
bobie

**Comment by homanp** [comment]
hey @bchen-twilio 
Going really well with the app! We register about 600 calls per day now and growing every day!
Awesome work, will check it out!

Thanks

**Comment by bchen-twilio** [comment]
@homanp 
THAT IS TOTALLY AWESOME!
We are working on a significant object model change, which is to consolidate the incoming & outgoing call objects and try to make app developers' life easier.
We'll include the update in the next release, but let me know if you would like to give it a try to see if it really is a better design.
I'll leave this ticket open and you are more than welcome to leave your feedback here.

Thanks
bobie

**Comment by gmpanuku** [comment]
hey @bchen-twilio 
I have been set up every thing and ran the project, But i am getting below two error always.
**error 1: An error occurred while registering: Error Domain=com.twilio.TVONotificationClient Code=31301 "Failed to register. Code: 5." UserInfo={NSLocalizedDescription=Failed to register. Code: 5.}**

**error 2: outgoingCall:didFailWithError: Twilio Services Error**

I am unable to call, can you please help me to resolve these issues.

Thanks.

**Comment by bchen-twilio** [comment]
Hey @homanp 

How's it going? not sure if you've noticed but we've just released our iOS Voice SDK 2.0.0-beta6 yesterday. Here is the [changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog). Are you can see in the quickstart samples, we've also introduced significant updates to the object model. It'd be great if you give it a try and let us know how goes.

Cheers
-bobie

**Comment by bchen-twilio** [comment]
Closing this issue. Please feel free to re-open or create a new issue in the future.
Thanks.
