### ISSUE TITLE
Call received on multiple devices

### ISSUE THREAD

**Issue by marioacarvalho** [twilio/voice-callkit-quickstart-objc#8]
Hi guys,

is there any way to unregister all devices for a certain user? 

My problem here is:

- I register user A on device A.
- I register user B on device B.
- I register user C on device C.

Until here everything ok. Now if I:

- Use user C on device A.
- If B calls to C, both phone A and C start ringing.

My sugestion here is to develop some function to unregister all IDs to some user.. Is this possible?

Thanks,

Mário

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho 

Great question. The Twilio Voice (mobile) SDKs allow **"multiple devices to be registered w/ the same identity"** and as you saw Twilio Voice service will fan out call-invite notifications to all of them. One of them reacts (accept/reject), the rest of them will all be notified with a `cancelled` notification. (actually the one reacts will also get a cancel notification but the SDK will ignore it since the payload contains a identical call-SID)

We do plan to provide a visualized tool in the Twilio dev console so that developers can view and manage active bindings.

-bobie

**Comment by marioacarvalho** [comment]
> We do plan to provide a visualized tool in the Twilio dev console so that developers can view and manage active bindings.

I get this but when we have more than 100k users to manage won't be easy to manage active bindings.

But my main problem is when I call to someone that used my device before! I'm listening both out call and in call....

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho 

I understand your concern.
This could easily happen during the development phase and I would like to know that is it very likely that your end users register with the same identities?

Currently the system is designed to maintain bindings using the combination of `device token` + `identity`, for example:
- in your app (on the same device), you register with identity `A`
- later you decide to change the name and register again with identity `B`
The push binding for identity `A` will be killed and this device will only be push-reachable via binding `B`.

The reason we design this is to provide user with higher flexibility. An example is that an end user might want to log all of his/her mobile devices and the browser client to be able to receive notifications everywhere.

-bobie

**Comment by marioacarvalho** [comment]
> later you decide to change the name and register again with identity B
The push binding for identity A will be killed and this device will only be push-reachable via binding B.

Currently this is not happening! I have 1 device that receives calls from multiple Identities.

**Comment by bchen-twilio** [comment]
> I have 1 device that receives calls from multiple Identities.

Hey @marioacarvalho 
Could you share us the steps of how you registered with multiple identities and were able to receive calls for all of the identities?

I've tried to register, on the same device/app, with a different identity and calling the original identity no longer works. Here are my steps:
- launch the app and register as `A`
- use another client to call `A` and `A` was able to receive a call
- change the identity to `B` by calling `VoiceClient.registerWithAccessToken:deviceToken:completion:`. i didn't call any unregister in the application.
- make another call to `A`. this time the app should not receive any incoming call push and the call should fail immediately on the caller side
- make a call to `B` and i did receive the call

Let me know if this is the same at your side.
Thanks.

**Comment by marioacarvalho** [comment]
I can receive the call here:

> - make another call to A. this time the app should not receive any incoming call push and the call should fail immediately on the caller side

Could this be Android caused by Android Voice SDK? Because I keep receive calls on Android Device and not on iOS.

This is what I've done:

- Register on Android with `A`
- Change identity to `B`
- Register on iOS with `A`
- Call from `B` to `A` leads to call received on `B` (Android) instead of iOS.

Again, could it be an Android issue?

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho 

Thanks for the details.
We've just tried the same steps with both the Android testapp and the iOS testapp, and the result was as we expected - the call from B (Android) to A (iOS) worked well.

Could it be that although you tried to specify a different identity for another client, the identity in the access token is actually not updated? A quick way to check is to feed the access token string into [jwt.io](https://jwt.io/) and you will see what is the identity embedded in the token.

It would also be great if you could share the codes, Android and iOS, of how you "change the identity" in your applications.

Thanks.

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho 

How are things? we are wondering if you are still seeing the same problem in your environment or is this no longer an issue for you?

We've recently combined regular quickstart and CallKit quickstart into the same repo (https://github.com/twilio/voice-quickstart-objc) and we are going to close this repo soon. I am going to close this ticket for now, but please feel free to open a new issue in these two repositories:
https://github.com/twilio/voice-quickstart-objc
https://github.com/twilio/voice-quickstart-swift

Thanks again for choosing the Twilio Voice SDK.

-bobie
